# src/utils/__init__.py
"""
Utilities Module for SVELTE Framework.
Provides file I/O operations, serialization, and utility functions.
"""

from .file_io import (
    read_binary_file,
    read_binary_chunk,
    write_binary_file,
    memory_map_file,
    stream_binary_file,
    write_json,
    read_json,
    write_compressed_json,
    read_compressed_json,
    write_pickle,
    read_pickle,
    write_csv,
    read_csv,
    write_numpy_array,
    read_numpy_array,
    ensure_dir,
    copy_file,
    move_file,
    read_lines,
    write_lines,
    read_struct,
    write_struct,
    safe_remove,
    safe_remove_dir,
    list_files,
    get_file_info,
    file_size,
    is_json_file,
    is_binary_file,
    create_backup,
    cleanup_temp_files,
    sync_directories,
    FileIOException,
    FileChecksum
)

__all__ = [
    'read_binary_file',
    'read_binary_chunk',
    'write_binary_file',
    'memory_map_file',
    'stream_binary_file',
    'write_json',
    'read_json',
    'write_compressed_json',
    'read_compressed_json',
    'write_pickle',
    'read_pickle',
    'write_csv',
    'read_csv',
    'write_numpy_array',
    'read_numpy_array',
    'ensure_dir',
    'copy_file',
    'move_file',
    'read_lines',
    'write_lines',
    'read_struct',
    'write_struct',
    'safe_remove',
    'safe_remove_dir',
    'list_files',
    'get_file_info',
    'file_size',
    'is_json_file',
    'is_binary_file',
    'create_backup',
    'cleanup_temp_files',
    'sync_directories',
    'FileIOException',
    'FileChecksum'
]

__version__ = '1.0.0'